config/routes.rb
SampleApp::Application.routes.draw do
  resources :categories

  get "pages/home"

  get "pages/contact"
  
  get "pages/about"

  root :to => 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  attr_accessible :id, :name, :parent_id, :rgt, :lft ,:depth    
  
  # Behaviours
  acts_as_nested_set

  # Callbacks
  after_save :update_depth

  # Validations
  validates_presence_of :name
  validates_uniqueness_of :name

  def update_depth
    unless self.level == self.depth
      self.update_attribute(:depth, self.level)
      self.children.each{|child| child.update_depth }
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  
  def restructure
    _parent = Category.find(params[:category_id].gsub('category_',''))
    _child = Category.find(params[:subcategory_id].gsub('category_',''))
    _child.move_to_child_of(_parent)
    _child.update_depth
    @categories = Category.roots
    render :partial => 'categories_tree'
  end
  
  def index
    @categories = Category.roots
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title="Home"
  end

  def contact
    @title="Contact"
  end
  
  def about
    @title="About"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title
    base_title = "Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"    
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_categories_tree.html.erb
<%- @categories.each do |category| -%>
  <%= render :partial => 'category_row', :locals => {:category => category} -%>
<%- end -%>

app/views/categories/_category_row.html.erb
<tr class="<%= cycle('odd', 'even') -%>" style="cursor: move;"  id="category_<%= category.id -%>">
  <td style="padding-left: <%= (1 * category.level) + 1 -%>em;">
    <%=h category.name -%>
  </td>
  <td>
    <%= link_to 'Show', category -%> | 
    <%= link_to 'Edit', edit_category_path(category) -%>
  </td>
</tr>
<%= draggable_element(
      "category_#{category.id}",
      :ghosting => true,
      :revert => true
    ) 
-%>
<%= drop_receiving_element(
       "category_#{category.id}",
       :update => 'catlist',
       :with => "'subcategory_id=' + element.id",
       :url => { :action => 'restructure', :category_id => category.id },
       :hoverclass => "row_highlight"
     )
-%>
<%- category.children.each do |subcat| -%>
  <%= render :partial => 'category_row', :locals => {:category => subcat} -%>
<%- end -%>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<%- if @categories.empty? -%>
  <p><em>No categories have been created yet.</em></p>
<%- else -%>
  <br />
  <table>
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody id="catlist">
      <%= render :partial => 'categories_tree' -%>
    </tbody>
  </table>
<%- end -%>
<br />
<%= link_to 'New Category', new_category_path -%>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>PAGES#ABOUT</h1>

added manually

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>